### ISSUE TITLE
Grup Name tidak valid

### ISSUE THREAD

**Issue by Madangkara** [WhatsAppNETClient/WhatsAppNETAPINodeJs2#2]
Selamat malam pak. 

Mau lapor bug saat baca nama grup dapatnya nama pengirim pesan digrup tersebut.
Untuk grup.id sudah benar tp grup.name isinya nama orang yg tulis chat.

Terima Kasih

**Comment by WhatsAppNETClient** [comment]
Sudah diperbaiki, silahkan update project https://github.com/WhatsAppNETClient/WhatsAppNETAPINodeJs2
